import {test,expect} from '@playwright/test';
test('aggregate evidence, CRM representation, barriers, persistence and export',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:'+ New decision',exact:true}).click();await page.getByRole('button',{name:'Fill example',exact:true}).click();await page.getByRole('button',{name:'Create decision model →',exact:true}).click();await expect(page.getByText('Orchestrator response',{exact:true})).toBeVisible();await page.locator('nav [data-page=aircrewpage]').click();
 const form=page.locator('#operations-form');for(const[k,v]of Object.entries({platform_type:'Synthetic training aircraft',identifier:'Assurance example',phase:'Organizational review',situation:'Reconcile cross-system evidence',observations:'Synthetic aggregate data'}))await form.locator(`[name=${k}]`).fill(v);
 await page.getByRole('button',{name:'Enable aviation coordination review',exact:true}).click();await form.locator('[name=ac_as_of]').fill('2026-10-03');
 for(const row of await form.locator('[data-aviation-check]').all())await row.locator('[name=review_on]').fill('2026-10-10');
 for(const scope of ['airport','aircraft','command_team','operations']){await page.getByRole('button',{name:'Add security technology project',exact:true}).click();const row=form.locator('[data-as-project]').last();for(const[k,v]of Object.entries({name:'Synthetic '+scope+' security',asset_and_interface:'Fictional test interface',review_on:'2026-10-10',next_action:'Run isolated test'}))await row.locator(`[name=${k}]`).fill(v);await row.locator('[name=scope]').selectOption(scope);await row.locator('[name=stage]').selectOption('validation');await row.locator('[name=technology]').selectOption(scope==='aircraft'?'qkd_research':'post_quantum');}
 await page.getByRole('button',{name:'Enable aggregate evidence and CRM review',exact:true}).click();await page.getByRole('button',{name:'Add synthetic measure',exact:true}).click();
 await page.getByRole('button',{name:'Add joint CRM exercise',exact:true}).click();const exercise=page.locator('[data-assurance-exercise]');
 for(const[k,v]of Object.entries({name:'Joint simulation debrief',conducted_on:'2026-10-02',scenario_reference:'Synthetic approved exercise',facilitator:'Training lead',debrief_reference:'Synthetic debrief',required_functions:'flight_deck, cabin, dispatch',represented_functions:'flight_deck, cabin'}))await exercise.locator(`[name=${k}]`).fill(v);
 await exercise.getByText('Integrated skills and training follow-up (optional)',{exact:true}).click();
 for(const[k,v]of Object.entries({tr_technical_objective:'Approved simulator task',tr_teamwork_objective:'Cross-check communication',tr_invited:'10',tr_attended:'4',tr_transfer_review_on:'2026-10-03'}))await exercise.locator(`[name=${k}]`).fill(v);
 await exercise.locator('[name=followup_disposition]').selectOption('no_actions_identified');
 await page.getByRole('button',{name:'Add implementation barrier',exact:true}).click();const barrier=page.locator('[data-assurance-barrier]');
 await barrier.locator('[name=status]').selectOption('addressed');for(const[k,v]of Object.entries({owner:'Safety lead',review_on:'2026-10-10',evidence:'Synthetic governance review',corrective_action:'Obtain operational feedback'}))await barrier.locator(`[name=${k}]`).fill(v);
 await barrier.getByText('Reciprocal feedback and resource evidence',{exact:true}).click();await barrier.locator('[name=outbound_reference]').fill('Synthetic outbound memo');
 await page.getByRole('button',{name:'Add investigation hypothesis',exact:true}).click();const hypothesis=page.locator('[data-assurance-investigation]');
 for(const[k,v]of Object.entries({name:'Handoff interruption hypothesis',hypothesis:'Interruptions may affect handoff completeness',reported_observations:'Synthetic missing acknowledgements',source_reference:'Synthetic source extract',review_owner:'Investigation lead',review_on:'2026-10-02'}))await hypothesis.locator(`[name=${k}]`).fill(v);
 await hypothesis.locator('[name=perspective]').selectOption('coordination');await hypothesis.locator('[name=disposition]').selectOption('consistent');
 const pending=page.waitForResponse(r=>r.url().endsWith('/operations-incidents')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save incident assessment',exact:true}).click();const response=await pending;expect(response.status(),await response.text()).toBe(201);const a=(await response.json()).analysis.coordination.evidence_review;
 expect(a.exercises[0].training.attendance_percent).toBe(40);expect(a.exercises[0].training.gaps).toContain('Practice transfer evidence due');
 expect(a.measures[0].current_per_1000).toBe(4);expect(a.measures[0].rate_change_per_1000).toBe(2);expect(a.exercises[0].missing_functions).toEqual(['dispatch']);expect(a.barriers[0].status).toBe('review_required');expect(a.investigations[0].causal_status).toBe('not_established');expect(a.investigations[0].gaps).toContain('Missing alternative explanation');
 await expect(page.locator('.assurance-results')).toContainText('No evidence of response returned');await page.reload();await page.locator('nav [data-page=aircrewpage]').click();await expect(page.locator('.assurance-results')).toContainText('Joint simulation debrief');await expect(page.locator('.training-results')).toContainText('Cross-check communication');await expect(page.locator('.investigation-results')).toContainText('Handoff interruption hypothesis');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download incident handover',exact:true}).click();expect((await download).suggestedFilename()).toContain('aviation-handover');
 await expect(page.locator('.aviation-security-results')).toContainText('Synthetic airport security');await expect(page.locator('.aviation-security-results')).toContainText('Synthetic command_team security');await expect(page.locator('.aviation-security-results')).toContainText('Missing qkd link and failure reference');await expect(page.locator('.aviation-security-results')).toContainText('Missing safety and authority reference');
 await page.locator('.assurance-results').scrollIntoViewIfNeeded();await page.screenshot({path:'../../.test-tmp/aviation-evidence-results.png'});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
