const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8895/');await page.getByRole('button',{name:'+ New decision',exact:true}).click();await page.getByRole('button',{name:'Fill example',exact:true}).click();await page.getByRole('button',{name:'Create decision model →',exact:true}).click();await page.getByText('Orchestrator response',{exact:true}).waitFor();await page.locator('nav [data-page=computepage]').click();
 const f=page.locator('#compute-form');await f.locator('[name=samples]').fill('500');
 for(const field of await f.locator('[data-compute-option]').all()){for(const range of await field.locator('[data-range]').all()){const kind=(await range.getAttribute('data-range')).split(':')[1];await range.fill({low:'3',likely:'6',high:'9'}[kind]);}await field.locator('[name=source]').fill('Test assumptions');for(const check of await field.locator('[data-check]').all())await check.selectOption('pass');}
 const saved=page.waitForResponse(r=>r.url().endsWith('/compute'));await page.getByRole('button',{name:'Compute & save decision analysis',exact:true}).click();assert.equal((await saved).status(),201);await page.getByRole('heading',{name:'Decision analysis · revision 1',exact:true}).waitFor();
 await page.getByRole('heading',{name:'Exact range analysis',exact:true}).waitFor();await page.getByText('Lowest worst-case regret:',{exact:false}).waitFor();
 await page.reload();await page.locator('nav [data-page=computepage]').click();await page.getByRole('heading',{name:'Decision analysis · revision 1',exact:true}).waitFor();await page.getByRole('heading',{name:'Exact range analysis',exact:true}).waitFor();
 await page.locator('[data-suggestion] [data-reject]').click();await page.locator('[data-suggestion] textarea').fill('Too risky');await page.getByRole('button',{name:'Generate updated suggestion',exact:true}).click();await page.getByRole('heading',{name:'Updated suggestion',exact:true}).waitFor();
 const visual=page.locator('[data-compute-visual]');await visual.getByRole('heading',{name:'Performance and downside',exact:true}).waitFor();
 const slider=visual.locator('[data-sensitivity]').first();await slider.fill('25');await slider.dispatchEvent('input');assert.match(await visual.locator('[data-sensitivity-results]').innerText(),/Preview leaders/);
 const observation=visual.locator('[data-compute-observation]');for(const score of await observation.locator('[data-actual-score]').all())await score.fill('7');await observation.locator('[name=observed_on]').fill('2026-10-01');await observation.locator('[name=source]').fill('Measured browser test');await observation.locator('[name=lesson]').fill('Compare against original rubric');
 const observed=page.waitForResponse(r=>r.url().endsWith('/compute-observations'));await observation.getByRole('button',{name:'Save prediction feedback'}).click();assert.equal((await observed).status(),201);await page.getByText('Signed score error:',{exact:false}).waitFor();
 await page.locator('#compute-load').selectOption({index:1});await page.getByRole('button',{name:'Load inputs for a new analysis'}).click();await page.locator('#compute-form [name=scenario]').selectOption('adverse');await page.locator('#compute-form [name=scenario_note]').fill('Reduced capacity');
 const scenarioSaved=page.waitForResponse(r=>r.url().endsWith('/compute'));await page.getByRole('button',{name:'Compute & save decision analysis',exact:true}).click();assert.equal((await scenarioSaved).status(),201);await page.getByRole('cell',{name:'Reduced capacity',exact:true}).waitFor();
 await page.reload();await page.locator('nav [data-page=computepage]').click();await page.getByRole('cell',{name:'Reduced capacity',exact:true}).waitFor();await page.getByText('Signed score error:',{exact:false}).waitFor();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('Charts, sensitivity, evidence inputs, observed feedback, scenario comparison, persistence and mobile layout passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
