import {test,expect} from '@playwright/test';
test('IMF pilot saves, reloads, exports and fits mobile',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByRole('button',{name:'+ New decision',exact:true}).click();
 await page.getByRole('button',{name:'Fill example',exact:true}).click();
 await page.getByRole('button',{name:'Create decision model →',exact:true}).click();
 await expect(page.getByText('Orchestrator response',{exact:true})).toBeVisible();
 await page.locator('nav [data-page=imfpage]').click();
 for(const key of ['title','geography','problem','technology','alternative','owner','evidence','safeguards','pilot','evaluation'])await page.locator(`#imf-form [name=${key}]`).fill(key==='title'?'Macro data pilot':'Owned review evidence');
 await page.locator('[name=as_of]').fill('2026-10-04');
 for(const [key,value] of Object.entries({name:'Inflation',unit:'percent',value:'3',reference_period:'2026-08',released_on:'2026-09-04',source:'Statistical agency',vintage:'September release',owner:'Data reviewer',max_age_days:'29'}))await page.locator(`[name=obs_${key}]`).fill(value);
 await page.locator('[name=governance_review]').fill('Dated quota evidence and reform authority pending');
 await page.locator('[name=condition_target_type]').selectOption('quantitative_performance_criterion');
 await page.locator('[name=condition_impact_assessment]').fill('Independent assessment proposed; subgroup review pending');
 await page.locator('[name=condition_budget_execution]').fill('Allocation recorded; facility reconciliation pending');
 await page.locator('[name=condition_fiscal_ceiling_alignment]').fill('Deficit ceiling recorded; adjustor review pending');
 await page.locator('[name=condition_treasury_cash]').fill('TSA coverage recorded; release timing unresolved');
 await page.locator('[name=condition_reporting_latency]').fill('Live reporting claimed; event timestamps pending');
 await page.locator('[name=condition_backlog_recovery]').fill('Offline backlog reported; recovery unverified');
 await page.locator('[name=condition_procurement_exception_review]').fill('Duplicate invoice alert; independent review pending');
 await page.locator('[name=condition_retrospective_adjustments]').fill('Late posting recorded; reason under review');
 await page.locator('[name=condition_advance_recovery]').fill('Advance outstanding; milestone under review');
 await page.locator('[name=condition_payment_change_verification]').fill('Change request received; independent confirmation pending');
 await page.locator('[name=condition_retry_idempotency]').fill('Stable intent proposed; duplicate test pending');
 await page.locator('[name=condition_playbook_version_review]').fill('Draft v1; failure tests pending');
 await page.locator('[name=condition_checkpoint_atomicity]').fill('Checkpoint proposed; crash tests pending');
 await page.locator('[name=condition_webhook_event_review]').fill('Signature policy proposed; replay tests pending');
 await page.locator('[name=condition_backoff_convergence_evaluation]').fill('Lower abort rates claimed; baseline comparison pending');
 await page.locator('[name=condition_divergence_window_review]').fill('Settlement lag under review; deadline pending');
 await page.locator('[name=condition_isolation_flow_control]').fill('Recovery batch limit proposed; saturation test pending');
 await page.locator('[name=condition_threshold_calibration]').fill('Burst limit proposed; recovery load test pending');
 await page.locator('[name=condition_velocity_accounting]').fill('Quota reservation proposed; concurrency tests pending');
 await page.locator('[name=condition_failure_classification]').fill('Malformed payload isolated; routing examples pending');
 await page.locator('[name=condition_dlq_replay_review]').fill('Quarantined; key expiry review pending');
 for(const [key,value] of Object.entries({scope:'Health budget',currency_unit:'LCU millions',baseline_period:'2025',current_period:'2026',baseline_spending:'100',actual_spending:'110',nominal_floor:'105',baseline_price_index:'100',current_price_index:'125',comparability_evidence:'Same scope and full-year coverage',source:'Budget and CPI release'}))await page.locator(`[name=social_${key}]`).fill(value);
 await page.getByRole('button',{name:'Save IMF pilot'}).click();
 await expect(page.locator('.record')).toContainText('Nominal floor: met; real spending change: -12.0%');
 await expect(page.locator('.record')).toContainText('authority waiver review evidence missing');
 await expect(page.locator('.record')).toContainText('facility verification evidence missing');
 await expect(page.locator('.record')).toContainText('external financing evidence missing');
 await expect(page.locator('.record')).toContainText('ledger reconciliation evidence missing');
 await expect(page.locator('.record')).toContainText('system coverage evidence missing');
 await expect(page.locator('.record')).toContainText('module handoffs evidence missing');
 await expect(page.locator('.record')).toContainText('audit trail integrity evidence missing');
 await expect(page.locator('.record')).toContainText('three way match evidence missing');
 await expect(page.locator('.record')).toContainText('supplier verification evidence missing');
 await expect(page.locator('.record')).toContainText('settlement channel review evidence missing');
 await expect(page.locator('.record')).toContainText('cross channel trace evidence missing');
 await expect(page.locator('.record')).toContainText('recovery escalation evidence missing');
 await expect(page.locator('.record')).toContainText('event log quality evidence missing');
 await expect(page.locator('.record')).toContainText('business repeat review evidence missing');
 await expect(page.locator('.record')).toContainText('retry budget review evidence missing');
 await expect(page.locator('.record')).toContainText('dlq diagnostic review evidence missing');
 await expect(page.locator('.record')).toContainText('retry load coordination evidence missing');
 await expect(page.locator('.record')).toContainText('durable quarantine handoff evidence missing');
 await expect(page.locator('.record')).toContainText('compensation decision review evidence missing');
 await expect(page.locator('.record')).toContainText('authoritative correction review evidence missing');
 await expect(page.locator('.record')).toContainText('Linked idempotency conflicts evidence missing');
 await expect(page.locator('.record')).toContainText('baseline spending comparator: 125.00');
 await expect(page.locator('.record')).toContainText('Inflation: overdue');
 await page.goto('/#imf');await expect(page.locator('.record')).toContainText('release age 30 days');
 await expect(page.locator('.record')).toContainText('September release');
 await expect(page.locator('.record')).toContainText('Quota reservation proposed; concurrency tests pending');
 await expect(page.locator('.record')).toContainText('Burst limit proposed; recovery load test pending');
 await expect(page.locator('.record')).toContainText('Recovery batch limit proposed; saturation test pending');
 await expect(page.locator('.record')).toContainText('Settlement lag under review; deadline pending');
 await expect(page.locator('.record')).toContainText('Lower abort rates claimed; baseline comparison pending');
 await expect(page.locator('.record')).toContainText('real spending change: -12.0%');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export IMF pilot'}).click();
 expect((await download).suggestedFilename()).toBe('praxis-imf-pilot.json');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});

