import {test,expect} from '@playwright/test';
test('policy starter integration: scenario math, persistence and mobile',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByRole('button',{name:'+ New decision',exact:true}).click();
  await page.getByRole('button',{name:'Fill example',exact:true}).click();
  await page.getByRole('button',{name:'Create decision model →',exact:true}).click();
  await expect(page.getByText('Orchestrator response',{exact:true})).toBeVisible();
  await page.locator('nav [data-page=policypage]').click();
  await page.getByRole('button',{name:'Fill illustrative infrastructure example',exact:true}).click();
  await expect(page.locator('#policy-country')).toContainText('India');
  const response=page.waitForResponse(r=>r.url().endsWith('/v1/decisions/analyze'));
  await page.getByRole('button',{name:'Compare policies',exact:true}).click();
  const a=await (await response).json();expect(a.results[0].expected_score).toBeCloseTo(20.4375);
  await expect(page.locator('#policy-output')).toContainText('13.74');
  const f=page.locator('#policy-scorecard');
  await f.locator('[data-policy-scenario="0"] [name=scenario-probability]').fill('0.9');
  const invalid=page.waitForResponse(r=>r.url().endsWith('/v1/decisions/analyze'));
  await page.getByRole('button',{name:'Compare policies',exact:true}).click();
  expect((await invalid).status()).toBe(422);
  await f.locator('[data-policy-scenario="0"] [name=scenario-probability]').fill('0.35');
  const saved=page.waitForResponse(r=>r.url().endsWith('/policy-comparisons'));
  await page.getByRole('button',{name:'Compare & save to active decision',exact:true}).click();
  expect((await saved).status()).toBe(201);
  await expect(page.getByText(/How should the government compare.*revision 1/)).toBeVisible();
  await page.reload();await page.locator('nav [data-page=policypage]').click();
  await expect(page.getByText(/How should the government compare.*revision 1/)).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
