import {test,expect} from '@playwright/test';
test('World Bank solution saves, reloads, exports and fits mobile',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByRole('button',{name:'+ New decision',exact:true}).click();
 await page.getByRole('button',{name:'Fill example',exact:true}).click();
 await page.getByRole('button',{name:'Create decision model →',exact:true}).click();
 await expect(page.getByText('Orchestrator response',{exact:true})).toBeVisible();
 await page.locator('nav [data-page=worldbankpage]').click();
 await page.locator('#world-bank-form [name=area]').selectOption('financial_inclusion');
 for(const name of ['title','geography','problem','beneficiaries','technology','alternative','owner','evidence','safeguards','pilot','baseline','target','review_date'])await page.locator(`#world-bank-form [name=${name}]`).fill(name==='title'?'Debt transparency pilot':'Supplied review evidence');
 await page.locator('[name=stage]').selectOption('handover');
 await page.locator('#wb-finance-enabled').check();
 await page.locator('[name=finance_instrument]').selectOption('guarantee');
 await page.locator('[name=finance_sunset_terms]').fill('Review after pilot; owner must approve exit');
 await page.locator('[name=finance_public_upside]').fill('Proposed public profit share; independent valuation pending');
 await page.locator('#wb-monitoring-enabled').check();
 await page.locator('[name=finance_reported_milestone]').selectOption('met');
 await page.locator('[name=finance_outcome_observations]').fill('Reported improvement; attribution uncertain');
 await page.locator('[name=finance_covenant_binding]').fill('Draft public-access clause; counsel review pending');
 await page.locator('[name=finance_graduated_sanctions]').fill('Proposed warning then cure review; no action authorized');
 await page.locator('[name=finance_grievance_record]').fill('Complaint reference only; breach assessment pending');
 await page.locator('[name=finance_detection_remedy_handoff]').fill('Complaint received; independent review pending');
 await page.locator('[name=finance_grievance_disposition]').fill('Dismissed; appeal pending, compliance unresolved');
 await page.locator('[name=finance_acceleration_safeguards]').fill('Notice and cure proposed; collateral rights unverified');
 await page.locator('[name=finance_audit_precision]').fill('Validation sample and false-positive review pending');
 await page.locator('[name=finance_alternative_data_review]').fill('Consent recorded; data accuracy review pending');
 await page.locator('[name=finance_adverse_disclosure]').fill('Reasons recorded; comprehension review pending');
 await page.locator('[name=finance_access_after_remedy]').fill('Review conducted; access outcomes not established');
 await page.locator('[name=finance_structural_remediation]').fill('Independent override authority proposed; validation pending');
 await page.locator('[name=finance_appeal_change_trace]').fill('Case reference linked to proposed model change; validation pending');
 await page.locator('[name=finance_less_discriminatory_alternatives]').fill('Candidate comparison pending; no model selected');
 await page.locator('[name=finance_supervisory_mandate]').fill('Authority reference recorded; applicable scope pending');
 for(const [key,value] of Object.entries({name:'Service delay',unit:'days',baseline:'10',target:'2',actual:'6',observed_on:'2026-09-01',source:'Independent survey',owner:'Pilot team'}))await page.locator(`[name=result_${key}]`).fill(value);
 await page.locator('[name=results_as_of]').fill('2026-10-04');
 await page.getByRole('button',{name:'Save solution proposal'}).click();
 await expect(page.locator('.record')).toContainText('50.0% toward target');
 await expect(page.locator('.record')).toContainText('prototype evidence missing');
 await expect(page.locator('.record')).toContainText('additionality evidence missing');
 await expect(page.locator('.record')).toContainText('concessionality calibration evidence missing');
 await expect(page.locator('.record')).toContainText('independent verification evidence missing');
 await expect(page.locator('.record')).toContainText('beneficiary standing evidence missing');
 await expect(page.locator('.record')).toContainText('proportionality review evidence missing');
 await expect(page.locator('.record')).toContainText('breach assessment evidence missing');
 await expect(page.locator('.record')).toContainText('post monitor followup evidence missing');
 await expect(page.locator('.record')).toContainText('detection assumptions evidence missing');
 await expect(page.locator('.record')).toContainText('automation redress evidence missing');
 await expect(page.locator('.record')).toContainText('adjudication delays evidence missing');
 await expect(page.locator('.record')).toContainText('auditor integrity evidence missing');
 await expect(page.locator('.record')).toContainText('safe access alternatives evidence missing');
 await expect(page.locator('.record')).toContainText('outcome bias audit evidence missing');
 await expect(page.locator('.record')).toContainText('substantive appeal evidence missing');
 await expect(page.locator('.record')).toContainText('recourse feasibility evidence missing');
 await expect(page.locator('.record')).toContainText('causal proxy review evidence missing');
 await expect(page.locator('.record')).toContainText('sensitive audit governance evidence missing');
 await expect(page.locator('.record')).toContainText('longitudinal access review evidence missing');
 await expect(page.locator('.record')).toContainText('commercial independence evidence missing');
 await page.goto('/#world-bank');await expect(page.locator('.record')).toContainText('Debt transparency pilot');
 await expect(page.locator('.record')).toContainText('observation age 33 days');
 await expect(page.locator('.record')).toContainText('Review after pilot; owner must approve exit');
 await expect(page.locator('.record')).toContainText('Proposed public profit share; independent valuation pending');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export solution proposal'}).click();
 expect((await download).suggestedFilename()).toBe('praxis-world-bank-solution.json');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
