names.computepage='Decision compute';
const computeButton=document.createElement('button');computeButton.dataset.page='computepage';computeButton.textContent='Decision compute';computeButton.onclick=()=>busy(computeButton,async()=>{await load();state.page='computepage';render();});$('nav').appendChild(computeButton);
let computeCriteria=['Benefit','Feasibility','Stakeholder impact'];
function computepage(){
 const heading=intro('PRAXIS OS / COMPUTATIONAL DECISIONS','Explore how robust your choice is.','Compare uncertainty, downside and regret using reproducible local calculations.');
 if(!state.workspace)return heading+noDecision();
 const d=state.workspace.revision.decision,runs=state.workspace.records.filter(r=>r.kind==='decision_compute').slice().reverse();
 return heading+`<section class="panel"><h2>Define the comparison</h2><button type="button" class="secondary" id="compute-country-template">Use country economics and justice criteria</button><p class="note">Local classical computation · up to 50,000 samples within a bounded workload. Exact interval bounds complement sampling. Rights and legal requirements belong in hard constraints, assessed separately from scores.</p><p>Every score measures desirability from 0 to 10; higher means better. For cost, score affordability. Enter ranges you can justify.</p><label>Criteria · one per line<textarea id="compute-criteria">${computeCriteria.map(esc).join('\n')}</textarea></label><button class="secondary" id="compute-apply">Apply criteria</button><form id="compute-form"><div class="two-col">${computeCriteria.map((c,i)=>`<label>${esc(c)} weight<input data-compute-weight="${i}" type="number" min="0.01" max="100" step="any" value="1" required></label>`).join('')}<label>Weight uncertainty (%)<input name="weight_uncertainty" type="number" min="0" max="90" step="any" value="20" required></label><label>Simulations<input name="samples" type="number" min="200" max="50000" value="2000" required></label><label>Seed<input name="seed" type="number" min="0" max="2147483647" value="42" required></label><label>Score dependence<select name="dependence"><option value="independent">Independent variation</option><option value="shared_shock">Common shock across all scores</option></select></label></div>${d.options.map((o,i)=>`<fieldset data-compute-option="${i}"><legend>${esc(o.name)}</legend><div class="comparison-scroll"><table><thead><tr><th>Criterion</th><th>Low</th><th>Most likely</th><th>High</th></tr></thead><tbody>${computeCriteria.map((c,j)=>`<tr><th>${esc(c)}</th>${['low','likely','high'].map(k=>`<td><input data-range="${j}:${k}" aria-label="${esc(o.name)} ${esc(c)} ${k}" type="number" min="0" max="10" step="any" required></td>`).join('')}</tr>`).join('')}</tbody></table></div><label>Evidence or rationale for these ranges<input name="source" required maxlength="2000"></label>${constraintFields(d.constraints)}</fieldset>`).join('')}<button class="primary" ${d.options.length<2?'disabled':''}>Compute & save decision analysis</button></form></section>${runs.map(computeRun).join('')}`;
}
function computeRun(run){
 const a=run.analysis,current=run.version===state.workspace.revision.version,related=new Set([run.id]);
 const bounds=a.interval_analysis;
 const exact=bounds?`<h3>Exact range analysis</h3><p>Range-stable leaders: <strong>${esc(bounds.range_stable_leaders.join(', ')||'None')}</strong>. Lowest worst-case regret: <strong>${esc(bounds.minimax_regret_leaders.join(', ')||'None')}</strong>.</p><div class="comparison-scroll"><table><thead><tr><th>Option</th><th>Exact score bounds</th><th>Worst-case regret</th></tr></thead><tbody>${bounds.options.map(o=>`<tr><th>${esc(o.option)}</th><td>${num(o.lower_bound.score)}–${num(o.upper_bound.score)}</td><td>${num(o.worst_case_regret)}</td></tr>`).join('')}</tbody></table></div><p>A range-stable option remains at least tied with every eligible alternative throughout the supplied interval envelope. These are bounds on your model, not real-world guarantees.</p><details><summary>Bound calculations and witness weights</summary><pre class="human-review-json">${esc(JSON.stringify(bounds,null,2))}</pre></details><p class="note">${esc(bounds.method)}</p>`:'';
 for(const r of state.workspace.records)if(r.kind==='suggestion_response'&&related.has(r.advice_id))related.add(r.id);
 return `<section class="panel"><h2>Decision analysis · revision ${run.version}${current?'':' · historical'}</h2><p>${a.samples} simulations · seed ${a.seed} · ${esc(a.dependence.replace('_',' '))}</p><div class="two-col"><p>Average leaders: <strong>${esc(a.mean_leaders.join(', ')||'None')}</strong></p><p>Downside leaders: <strong>${esc(a.downside_leaders.join(', ')||'None')}</strong></p><p>Lowest expected regret: <strong>${esc(a.regret_leaders.join(', ')||'None')}</strong></p><p>Perfect-information upper bound: ${a.perfect_information_upper_bound===null?'Unavailable':num(a.perfect_information_upper_bound)+' score points'}</p></div>${a.computation?`<p>Engine: ${esc(a.computation.engine)} · ${a.computation.pair_comparisons.toLocaleString()} pair comparisons. Input SHA-256: <code>${esc(a.computation.input_sha256)}</code></p><p class="note">${esc(a.computation.precision_note)}</p>`:''}${exact}${list(a.warnings)}<div class="comparison-scroll"><table><thead><tr><th>Option</th><th>Mean / 10</th><th>Monte Carlo standard error</th><th>P05–P95</th><th>Worst 5% mean</th><th>Best share</th><th>Mean regret</th></tr></thead><tbody>${a.options.map(o=>`<tr><th>${esc(o.option)}</th><td>${num(o.mean_score)}</td><td>${o.mean_score_standard_error===undefined?'Legacy run':num(o.mean_score_standard_error)}</td><td>${num(o.p05)}–${num(o.p95)}</td><td>${num(o.lower_tail_mean)}</td><td>${num(o.best_share*100)}%</td><td>${num(o.mean_regret)}</td></tr>`).join('')}</tbody></table></div><p>Best share is the fraction of modeled comparisons won, with ties split. It is not a real-world success probability.</p>${a.blocked.map(o=>`<p class="callout">${esc(o.option)} excluded: ${esc(o.reasons.join('; '))}</p>`).join('')}${a.options.filter(o=>o.robustly_dominated_by.length).map(o=>`<p>${esc(o.option)} is dominated across the supplied ranges by ${esc(o.robustly_dominated_by.join(', '))}.</p>`).join('')}<details><summary>When priorities change the ranking</summary>${a.weight_switches.map(s=>`<p>${esc(s.options.join(' versus '))}: ${esc(s.criterion)} weight ${num(s.weight_at_tie)} (${num(s.relative_change*100)}% from supplied weight) produces a tie at most-likely scores${s.within_weight_range?' · inside your uncertainty range':''}.</p>`).join('')||'<p>No positive one-criterion switch boundary.</p>'}</details><details><summary>Pairwise comparisons and original inputs</summary><pre class="human-review-json">${esc(JSON.stringify({pairwise:a.pairwise_win_share,inputs:run.inputs},null,2))}</pre></details><p>${esc(a.method)}</p><p class="note">${esc(a.limitations)}</p>${current?(state.workspace.suggestions||[]).filter(s=>related.has(s.id)).map(suggestionCard).join(''):''}</section>`;
}
function bindCompute(){
 $('#compute-country-template')?.addEventListener('click',()=>{computeCriteria=['Economic efficiency','Poverty reduction','Income equality','Access to essential services','Institutional feasibility','Environmental sustainability'];render();toast('Country criteria loaded. Supply evidence and assess rights and legal requirements as hard constraints.');});
 $('#compute-apply')?.addEventListener('click',()=>{const names=lines($('#compute-criteria').value);if(!names.length||names.length>10||names.some(n=>n.length>80)||new Set(names.map(n=>n.toLowerCase())).size!==names.length){toast('Use 1–10 distinct criteria, each at most 80 characters.',true);return;}computeCriteria=names;render();});
 $('#compute-form')?.addEventListener('submit',e=>{e.preventDefault();busy(e.submitter,async()=>{const f=e.target,data=Object.fromEntries(new FormData(f));const criteria=computeCriteria.map((name,i)=>({name,weight:Number(f.querySelector(`[data-compute-weight="${i}"]`).value)}));const options=Array.from(f.querySelectorAll('[data-compute-option]')).map(field=>({option:state.workspace.revision.decision.options[Number(field.dataset.computeOption)].name,source:field.querySelector('[name=source]').value,evidence_date:field.querySelector('[name=evidence_date]').value||null,evidence_status:field.querySelector('[name=evidence_status]').value,constraint_checks:inquiryChecks(field),scores:Object.fromEntries(computeCriteria.map((name,j)=>[name,Object.fromEntries(['low','likely','high'].map(k=>[k,Number(field.querySelector(`[data-range="${j}:${k}"]`).value)]))]))}));await api(`/v2/decisions/${state.selected}/compute`,{base_version:state.workspace.revision.version,criteria,options,weight_uncertainty:Number(data.weight_uncertainty)/100,samples:Number(data.samples),seed:Number(data.seed),dependence:data.dependence,scenario:data.scenario,scenario_note:data.scenario_note});await load();render();toast('Computational analysis saved with reproducible inputs.');});});
}
