function mcLedgerEditor(){return `<details><summary>Ledger proposal assessment (optional)</summary><p>Record a proposed architecture and compare it with a non-ledger alternative. Use authorized test references and reviewer-defined requirements.</p>${mcText('lp_architecture_and_scope','Ledger architecture, use case and scope')}${[['sensor_validation_reference','Independent sensor / input validation evidence'],['administrator_and_membership_reference','Membership, administrator authority and revocation review'],['contract_upgrade_reference','Contract audit, upgrade and rollback review'],['offline_recovery_reference','Disconnected operation and recovery test evidence'],['privacy_reference','Data minimization and privacy review'],['resource_measurement_reference','Compute, bandwidth and energy measurement evidence'],['non_ledger_alternative','Non-ledger alternative and trade-offs'],['latency_measurement_reference','Latency test scope and measurement evidence'],['latency_budget_reference','Reviewer-defined latency budget and applicability']].map(([k,l])=>mcText('lp_'+k,l)).join('')}${assuranceNumber('lp_measured_latency_ms','Measured latency (ms, optional)',false)}${assuranceNumber('lp_latency_budget_ms','Reviewer latency budget (ms, optional)',false)}<p>Recorded transactions do not establish sensor truth. This assessment does not deploy a ledger or execute bridge commands.</p></details>`;}
const mcLedgerEditorBefore=mcCyberControlEditor;
const mcCrossValidationEditorBefore=mcLedgerEditor;
mcLedgerEditor=function(){return mcCrossValidationEditorBefore().replace('<p>Recorded transactions do not establish sensor truth.',`<h5>Sensor validation to ledger evidence (optional)</h5>${[['sensor_independence_reference','Sensor independence, calibration and shared-failure review'],['disagreement_handling_reference','Rejected / disputed states and approved fallback test evidence'],['validation_to_anchor_reference','Validation decision linked to exact state, timestamp and model version'],['anchoring_receipt_reference','Receipt / identifier linking the recorded state to ledger evidence']].map(([k,l])=>mcText('lp_'+k,l)).join('')}<p>Use references to authorized test records. A receipt reference is supplied evidence; this app does not verify a signature, sensor state or ledger transaction.</p><p>Recorded transactions do not establish sensor truth.`);};
const mcSpoofingEditorBefore=mcLedgerEditor;
mcLedgerEditor=function(){return mcSpoofingEditorBefore().replace('<p>Recorded transactions do not establish sensor truth.',`<h5>Spoofing evidence review (optional)</h5>${[['spoofing_threat_scope','Threat scope: message tampering, replay, physical spoofing or combined'],['message_authentication_reference','Message origin / integrity validation evidence'],['replay_protection_reference','Replay / freshness validation evidence'],['physical_signal_validation_reference','Independent physical-signal validation evidence'],['vessel_applicability_reference','Applicability to the vessel, receiver and operating setting']].map(([k,l])=>mcText('lp_'+k,l)).join('')}<label>Validation setting<select name="lp_validation_setting"><option value="">Not supplied</option><option value="maritime_field">Maritime field</option><option value="maritime_simulation">Maritime simulation</option><option value="other_domain">Other domain</option><option value="unknown">Unknown</option></select></label><p>Distinguish the tested threat and setting. Other-domain measurements remain evidence to review, rather than vessel performance estimates.</p><p>Recorded transactions do not establish sensor truth.`);};
mcCyberControlEditor=function(){return mcLedgerEditorBefore().replace('<button type="button" class="secondary" data-mc-control-remove>',mcLedgerEditor()+'<button type="button" class="secondary" data-mc-control-remove>');};
function mcLedgerControlValues(row){const r=lrValues(row),p={};for(const k of Object.keys(r)){if(k.startsWith('lp_')){p[k.slice(3)]=r[k];delete r[k];}}if(Object.values(p).some(v=>v!==''&&v!==null))r.ledger_proposal=p;return r;}
const mcLedgerValuesBefore=mcCyberSystemValues;
mcCyberSystemValues=function(row){const r=mcLedgerValuesBefore(row);r.controls=[...row.querySelectorAll('[data-mc-control]')].map(mcLedgerControlValues);return r;};
const mcLedgerResultsBefore=maritimeCoordinationResults;
maritimeCoordinationResults=function(a){const html=mcLedgerResultsBefore(a);if(!a)return html;const proposals=(a.systems||[]).flatMap(s=>(s.control_analysis||[]).filter(c=>c.ledger_analysis).map(c=>({name:s.name,analysis:c.ledger_analysis})));return html.replace('<h4>Bridge drills</h4>',`${proposals.map(({name,analysis:p})=>`<section class="maritime-ledger-results callout"><h5>Ledger proposal: ${esc(name)}</h5><p>${esc(p.architecture_and_scope)}<br>${esc(p.status.replaceAll('_',' '))}</p>${list(p.gaps)}<p>Latency margin: ${p.latency_margin_ms===null?'Unavailable':num(p.latency_margin_ms)+' ms'}</p><details><summary>Architecture review evidence and alternatives</summary>${Object.entries(p).filter(([k,v])=>k.endsWith('_reference')||['non_ledger_alternative','spoofing_threat_scope','validation_setting'].includes(k)).map(([k,v])=>`<p><strong>${esc(k.replaceAll('_',' '))}:</strong> ${esc(v||'Not supplied')}</p>`).join('')}</details><p>${esc(p.method)}</p><p>Sensor truth and deployment authorization are not established.</p></section>`).join('')}<h4>Bridge drills</h4>`);};
